/*

Structural language learning and tandem method.
A JavaScript computer program for coaching.

Copyright (c) 2012 Antonio Bonifati http://ninuzzo.github.com/about.html

This work is licensed under the Creative Commons
Attribution-NonCommercial-ShareAlike 3.0 Unported License. To view a copy of
this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a
letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View,
California, 94041, USA.

*/

var title="here, there, over there, there is",
  date='2012-05-01', lk='en', l1='de', l2='it', lesson=
[
 ['def', "there", ["dort", "da"], ["là", "lì", "ci"], ["The choice between different translations of 'there' is idiomatic both in German and Italian. Rather than giving complex rules, we will learn it by example.", "Italian: 'la' without any accent mark is 'the' for a feminine thing, animal or person (only one thing). 'ci' before a word beginning with a vowel gets always elided into c'"]],
 ['def', "it", ["er", "sie", "es"], ["esso", "essa"], ["English: it is neuter. You use it when talking about a single thing (with some exceptions) or animal (especially if wild). For domesticated animals, English people use he/she.", "German: er for masculine things, sie for feminine things and es for neuter things. Only the gender of the noun counts and it must be memorized.", "Italian: 'esso' for masculine things/animals and 'essa' for feminine things/animals. 'Essa' for 'she' is sometimes found in literature or regional speaking, but in standard Italian better you say 'lei'. You can never say 'esso' to refer to a male, use 'lui'. For animals, formally, e.g. in a nature program, you will use 'esso', 'essa', but in spoken language, especially for your pets, you will often hear 'lui', 'lei', as they were personified :) NB There is no neuter in Italian."]],
 ['tra', "it is", "es ist", ["è", "esso è", "essa è"], "German: suppose we are referring to a neuter thing/animal/person. Yes, there are some neuter names relating to persons in German, e.g. 'das Mädchen' is not feminine as one would expect, despite it means 'girl'. In such case 'it' ('es') would be used to refer to the girl! Also another quite known German word for an unmarried 'young lady' is neuter too: das Fräulein. BTW Fräulein is not very used nowadays, Mädchen is more common."],
 ['def', "true", "wahr", "vero"],
 ['tra', "it is true", "es ist wahr", "è vero"],
 ['def', "false", "falsch", "falso"],
 ['tra', "it isn't false, it is true", "es ist nicht falsch, es ist wahr", "non è falso, è vero"],
 ['def', "it is there", ["es ist da", "es ist dort"], ["è lì", "è là"], ["German: 'da', which also has other different meanings in German, in this sentence means 'there' in a sort of undefined way, while 'dort' is a specific 'there', a place you could point your finger at (a 'fixed' location) and far away from you (like 'over there', 'in that place' in English, therefore it always implies a distance, someone/thing far away). 'Dort' is considered a bit more formal than 'da'.", "Italian: lì/là are almost equivalent. It is nuance that 'lì' denotes a more precise and not very far away place, while 'là' a more distant and indefinite place. You do not make a mistake if you use them interchangeably; a perfectionist would try to use 'là' for people or things that are rather distant (whenever 'over there' would fit too) and 'lì' for nearer things (there), but since there is no definite measure for what is near and what is far, not all native speakers are so finicky. As a matter of fact if something/somebody is very near, you would rather use the word for 'here' rather than the word for 'there' in any language."]],
 ['tra', "is it there?", ["ist es da?", "ist es dort?"], ["è lì?", "è là?"], ["German: interrogative intonation is optional, the inverted structure already signals it is a question.", "Italian: the interrogative tone is important, being the only way to tell a question from an affirmation when one is speaking, because no inversion occurs in Italian, nothing in structure changes and there is no other way to render the question mark in speaking."]],
 ['def', "here", ["hier", "da"], ["qui", "qua"], ["Again, let's illustrate word choice by examples!", "German: note the spelling for 'here' is a bit different as well as the pronunciation of the -r, which in German is a reduced or constricted 'a' sound, optionally followed by an 'r' sound. Note that 'da' means both 'there' and 'here' or it remains indeterminate, depending on the context, if it is stressed, and even where one is pointing or looking at. 'da' is a bit of an indeterminate word to denote a place. Indeed this kind of words are not very precise in any language, we are not taking measures in metres, but German 'da' takes indetermination to the extreme: neither Italian nor English have a single word that can mean both 'there' and 'here' as German has!"]],
 ['tra', "I am", "ich bin", "sono"],
 ['def', ["here!", "present!"], "ich bin da!", "presente!", "This is what children/students say in school when the teacher takes the register."],
 ['def', "it is here", ["es ist da", "es ist hier"], ["è qua", "è qui"], ["German: 'es ist da' can mean either 'it is here' and 'it is there', because 'da' is inderminate. In German, people often do not bother to be precise and use 'da' instead of 'hier'. To use 'hier' in German, you first have to make sure that you can show the object with your finger (or you have it in front of you).", "Italian: the subtle difference between 'qui' and 'qua' is the same difference between 'lì' and 'là'. The words ending with -i (qui, lì) denote a place more near and determinate than the word ending with -a (qua, là), which is less determinate and therefore possibly further away. But, similarly to Germans using 'da', most Italians do not worry about this difference and use them interchangeably. Anyway, in most cases the most appropriate translation for 'da' in Italian, when it means 'here',  is 'qua', because both 'da' and 'qua' are indeterminate, the German word 'da' being even more indeterminate than the Italian 'qua' - mnemonic: they both end in -a. And for 'hier', the most appropriate translation is 'qui', both rather determinate - mnemonic: there is an 'i' in both."]],
 ['tra', "isn't it here?", ["ist es nicht hier?", "ist das nicht hier?", "ist das hier nicht?"], ["non è qui?", "non è qua?"], ["German: das can used for 'it', that is instead of 'es'. It does not mean 'the' neuter in this case, but rather 'this'. 'da' can be used instead of 'hier' in all the German sentences above and corresponds to Italian 'qua', both being a bit indeterminate.", "Italian: structure is '(it) not is here?' or 'not is here (it)?'"]],
 ['tra', "here and there", "da und dort", "qua e là", ["German: in this case, 'da' translates 'here' (an indeterminate 'here') and dort means 'there', that is a place further away.", "Italian: for this expression, which is a set frase in Italian as in German and English, we use 'qua' and 'là' instead of 'qui' and 'lì' in order to express more indetermination. If you say 'qui e lì' or mixed 'qua e lì', they are not wrong in principle, but refer to places nearer or in a more more precise way. But 'here and there' is an expression that means 'in various places', 'around', so 'qua e là' is the more appropriate Italian translation."]],
 ['tra', "I am here", ["ich bin da", "ich bin hier"], ["sono qua", "sono qui"], "d-a, qu-a, l-à! When it ends in -a is a bit indeterminate both in German and Italian. h-i-er, qu-i, when there is an 'i' is it a bit more precise!"],
 ['tra', "I am there", ["ich bin da", "ich bin dort"], ["sono là", "sono lì"]],
 ['def', "I'm going there ((right) now)", ["ich gehe dahin jetzt", "ich gehe dorthin jetzt", "ich gehe jetzt dahin", "ich gehe jetzt dorthin"], ["vado lì adesso", "vado là adesso", "lì vado adesso", "là vado adesso", "ci vado adesso", "sto andando lì", "sto andando là", "lì sto andando", "là sto andando", "ci sto andando"], ["German: when 'there' implies 'to there', that is there is a movement toward the given location, a '-hin' suffix has to be added. In English and Italian 'there' is always 'there', it doesn't change or adds anything: I am there, I'm going there.", "Italian: '(I) go there now', '(I) there go now', '(I) am going there' or '(I) there go now'. If you have 'there' before a verb it can be either 'ci' or 'lì/là', usually the former, the latter is used only when one wants to put a stress on 'there', as if it were 'right there', 'there and not in another place'. 'there' after a verb is always 'lì/là'. In other words 'ci' can never be put after a verb, you cannot say 'vado ci', you have to say 'vado lì/là' or 'ci vado'. Instead of 'adesso' you can also use 'ora', with the same meaning. Both can be also put at the beginning of the sentence, you do that if you want to stress the word 'now'. When you use 'stare andando' for 'to be going', 'adesso/ora' is optional, because this form already implies 'right now' in this case. If you say 'là/lì vado', by using là or better lì instead of 'ci', putting it at the beginning and stressing it, you mean 'I am going right there'. There is a word for 'right' too: 'proprio' that you can add: 'proprio lì/là vado (adesso)' or 'proprio lì/là sto andando'."]],
 ['tra', "it is there", ["es ist da", "es ist dort"], ["è lì", "è là"]],
 ['def', "there is", ["da ist", "dort ist", "es gibt"], "c'è", ["In all three languages this construct is used to state the existence or presence of something/one. The choice between different translations in German will be shorty explained by examples, rather than overwhelming you now with complex rules!", "German: geb-en (to give) &rarr; (es) gib-t (it gives), 'e' irregularly becomes 'i'. 'es gibt', literally is 'it gives', but in German is also idiomatically to mean 'there is'. You would prefer to use 'es gibt' if you already knew before speaking that there is something/one, in other words it is not a discovery of the moment.", "Italian: '(lui, lei, esso/a) è là/lì' means '(he, she, it) is there'. If we want to say 'there is' we prefer to use another word for 'there' in this case: 'ci'. Anyway 'ci è' is never said as it is, we always elide it into c'è, but that c' is still 'ci'."]],
 ['def', "is it there?", "ist es da?", ["c'è?", "è là?"], "Let's suppose this is question, e.g. one is searching for something and another asks whether he has found it.", ["German: since who asks does not know whether the object is actually there or not, 'da' is used.", "Italian: for the same reason 'ci' is used, at most 'là', but not 'lì'. That would be rather used in an affirmative sentence when one has spotted something, 'it is there!', 'è lì!', 'es ist dort'."]],
 ['def', "they", "sie", ["loro", "essi", "esse"], ["German: 'sie' is both 'she' and 'they'.", "Italian: 'loro' for a group of people (in informal Italian in reference to animals too, but never use 'loro' to refer to a set of things!); 'essi' for a group of people/animals/things with at least one male, 'esse' for a group of people/animals/things made up of all females. For a group of people it is probably easier to use 'loro', indeed this is the new word which makes things simpler!"]],
 ['def', "they are", "sie sind", ["sono", "loro sono", "essi sono", "esse sono"], ["German: 'she is' is 'sie ist', while 'they are' is 'sie sind'. But 'Sie sind', with a capital 'S' for 'Sie' means 'you are', used in formal language instead of 'du bist'.", "Italian: 'sono', same word as 'I am', 'io sono'."]],
 ['tra', "they are here", ["sie sind da", "sie sind hier"], ["sono qua", "sono qui"], "If referred to people, it can mean 'they have just arrived'. In this meaning in German you would prefer 'da' and in Italian 'qua', unless the people who you are talking about are really here with you! In this latter case, you would prefer 'hier' and 'qui'."],
 ['tra', "they are there", ["sie sind da", "sie sind dort"], ["sono lì", "sono là"], "German: You can only see from the context and intonation whether 'sie sind da' means 'they are here'/'they have just arrived' an in previous slide or rather 'they are there' as in this slide. If there is no context, a neutral intonation and no showing with the finger, you can assume that 'da' means 'here': 'they are here', 'they have just arrived', as in the previous slide."],
 ['def', "over there", ["da drüben", "dort drüben"], "laggiù", ["Note 'over' in 'over there' does not mean 'up' or 'down' in English. If we want to say that, we say 'up there' or 'down there'. 'over' in 'over there' just means 'after you cross there, that place', 'over' means 'to cross', so 'over there' a bit further away than 'there', not necessarily up or down.", "German: the word for 'over' in this case is 'drüben', but word order is inverted: 'over there' is 'there over', 'da/dort drüben'. There is the usual difference between 'da' and 'dort' here too: 'dort' is always a kind of a pointer, 'da' can be a pointer or just mean that something is in a place, without pointing to it.", "Italian for 'over there' is actually 'theredown', where 'down' is 'giù', 'there' is 'là' and the 'g' of 'giù' is doubled to make a single word: 'laggiù'. 'laggiù' means either 'down there' and 'over there', depending on the context, 'giù' means 'down' (which is its literal meaning) but also 'over'. 'Liggiù' does not exist in Italian, but 'lì giù' is correct but does not mean 'over there', rather '(right) down there', 'in that precise place down there' - recall that 'lì' is more specific than 'là'."]],
 ['tra', "they are over there", ["sie sind da drüben", "sie sind dort drüben"], "sono laggiù"],
 ['tra', "what's there?", "was ist dort?", "cosa c'è lì?", "One says this while pointing in astonishment to a precise place in the sky, e.g. he has just seen an UFO!"],
 ['tra', "what is over there?", "was ist dort drüben?", "cosa c'è laggiù?", ["German: supposing we are pointing to something far away, dort is used and drüben intensifies the distance, just like 'over' in English.", "Italian: 'what there is over there?', the first 'there' is 'ci'. Recall 'what' can also be translated by 'che cosa' or only 'che'."]],
 ['def', "there are", ["da sind", "dort sind", "es gibt"], "ci sono", "Note unlike English and Italian 'es gibt' doesn't change, that is it can mean either 'there is' or 'there are'. The strange think to remember is that 'it gives' also means 'there is/are' in German!"],
 ['def', "Mr Bonifati is here", "Herr Bonifati ist da", "c'è il Signor Bonifati", "To say that something or someone is here, he has just arrived, in German 'da' is preferred. In this case 'da' clearly means 'here', that is relatively close and not 'there', but it is still a bit indeterminate, because we are not telling the exact location where the person is. Italian prefers to say 'there is', c'è: 'there is the mister Bonifati'. We prefer 'ci' in this case to 'qui/qua' or 'lì/là' because 'ci' is a bit more indeterminate than all the others (just like German 'da'), that is there is no pointing to a place when you say this sentence, you just want to say that someone has arrived. Of course, if you say 'Il Signor Bonifati è qua/qui' or 'Il Signor Bonifati è là/lì', it is not wrong, but, especially if you use lì or qui, one may reply, 'where?', 'dove?', expecting to be able to see him."],
 ['def', 'something', "etwas", ["qualcosa", "qualche cosa"], ["German: 'was' alone means 'what', it does not mean 'thing'. Et- is not a word by itself, but a prefix that means 'a bit/little', etwas is 'a bit of what'. The stress is on the 'e' of 'et', not the 'a' of 'was'.", "Italian: 'qualche' means 'some' and 'cosa' means 'thing'. Recall that 'what' in Italian is either 'che' (that),'che cosa' (that thing, meaning 'what thing') or simply 'cosa'. Something &rarr; qualche cosa &rarr; qualcosa. The one-word short form is preferred, but the two words form is acceptable too."]],
 ['tra', "there is something", ["da ist etwas", "dort ist etwas", "es gibt etwas"], "c'è qualcosa", "German: the difference between da/dort you already know: 'da' means either 'here' or 'not very far' and is thus a bit more indeterminate than 'dort'. But what is the difference between 'da/dort ist' and 'es gibt' now? Another quibble: they both mean 'there is', but you use 'da/dort ist' if you have discovered something on the fly, you can see it and you can point your finger at it. You use 'es gibt', if you already know what there is, you are not there to point your finger in astonishment or you are talking about an abstract thing."],
 ['tra', "there is something there", ["es ist etwas da", "es ist etwas dort"], "c'è qualcosa lì", "c'è qualcosa là", "lì c'è qualcosa", "là c'è qualcosa", "Italian: if you put lì/là at the beginning it's because you want to stress it."],
 ['def', "nothing", "nichts", ["niente", "nulla"], ["German: 'nothings' is 'nots', plural of 'not', 'nicht'. The final 'ts' sound has to be heard clearly.", "Italian: Note 'ie' in 'niente' sounds like 'ye' in 'yes', not like two separate 'i' and 'e' sounds. 'ente' means '(corporate/public) body' in Italian or 'being' in philosophy jargon. 'ni-' is a prefix meaning 'not'. So 'niente' seems to be similar to 'nobody', but it actually means 'nothing', we have another word for 'nobody' we will shortly see. Another equivalent word for nothing is 'nulla'. There is no meaning in Italian for 'ulla', because 'nulla' comes directly from Latin 'nullus'. In Latin 'ullus' means someone, so nulla means 'not someone'."]],
 ['def', ["there isn't anything", "there is nothing"], ["da ist nichts", "dort ist nichts", "es gibt nichts"], ["non c'è niente", "non c'è nulla"], ["English changes 'nothing' to 'anything' to avoid a double negation or doesn't use 'not' along with 'nothing'.", "German: another variant is 'das ist nichts', but that means 'it/that is nothing'.", "Italian: we actually say 'not there is nothing', negating two times (first 'non', and then 'ni-' of 'niente/nulla'). A double negation does not equate to an affirmation in Italian, the second ni- just intensifies the negation. 'non' cannot be left out in this case, that is c'è niente/nulla is wrong. In other words, we do not have a word fo anything, 'niente/nulla' means both 'nothing' and 'anything'."]],
 ['tra', "there's nothing there", ["es gibt nichts da", "da gibt es nichts", "da ist nichts"], ["non c'è niente lì", "non c'è niente là", "lì non c'è niente", "là non c'è niente"], "Italian: you can also use 'nulla'. They are interchangeable."],
 ['def', "there is nothing to do today", ["heute gibt es nichts zu tun", "es gibt heute nichts zu tun", "es gibt nichts zu tun heute"], ["oggi non c'è niente da fare", "non c'è niente da fare oggi"], "Both in German and Italian you stress heute/oggi by putting it at the beginning of the sentence. Again, you can also use 'nulla'."],
 ['tra', "it is nothing", ["es ist nichts", "das ist nichts"], ["non è niente", "è niente"], "Italian: unlike English and German we usually use 'not' along with 'nothing', although in this case, where the sentence means 'don't worry about it', you can leave 'not' off in Italian too. Again, you can also use 'nulla'."],
 ['tra', "it is nothing for me", "das ist nichts für mich", ["non è niente per me", "è niente per me"], "You can also use 'nulla'."],
 ['tra', "it isn't anything", "es ist nichts", ["non è niente", "non è nulla"], "Italian: same translation as 'it is nothing' with a double negation. Indeed the two sentences mean the same in English too."],
 ['def', ["no-one", "nobody"], ["niemand", "keiner"], "nessuno", ["German: 'ie' is a long 'i', -d sounds like 't'. 'man', which is found in 'nie-man-d', means 'one' impersonally in German. 'niemand' and 'keiner' are almost equivalent, the meaning is the same with a subtle different: 'keiner' refers to a particular group, selection or environment around you. 'niemand' is a bit stronger and refers to a general statement (e.g. the whole world). Germans are so precise! While 'niemand' is uncountable, 'keiner' is countable and an antonym is 'jeder'. The antonym for 'niemand' is 'alle'.", "Italian: 'uno', which is found in 'ness-uno' means 'one', both the number 1 and a way to refer to a person generically (impersonally) as if it were 'one (person)'. The latter meaning is used especially in the informal language in Italian, in formal language we have another word for German 'man', 'si' - not to be mistaken with 'sì', meaning 'yes'. 'nessuno', 'niente', 'nulla' are all uncountable. Note how both German and Italian translation correspond to 'no-one' in structure."]],
 ['tra', ["there isn't anybody here", "there is nobody here"], ["es ist keiner hier", "es ist niemand hier"], "non c'è nessuno qui", "German: 'it is nobody here' meaning 'there is nobody here'. 'keiner' is preferred since you mean 'around you', but 'niemand' can also be used, not all speakers are so precise."],
 ['def', ["is there anybody here?", "is there somebody here?"], ["ist irgendjemand hier?", "gibt es jemand hier?"], ["c'è nessuno qui?", "c'è nessuno qua?", "c'è qualcuno qui?", "c'è qualcuno qua?"], ["German: TODO", "In English you use anybody if you expect a negative answer (that is no answer in this case) and somebody if you think the answer will be 'yes' (that is somebody will answer!).", "In Italian, if you use 'nobody', 'nessuno' instead of 'somebody', 'qualcuno' you are bit more pessimistic, you probably think that nobody will answer. But do not expect someone to be logical and answer with 'no', you may be answered with 'sì' even if you used 'nessuno'. Italian for 'anybody/somebody' is 'qualcuno', literally someone. Note this word is similar to 'qualcosa', something."]],
 ['def', "here's Jola!", "da ist Jola!", "ecco Jola!", ["English: 'here' or 'there' can be used emphatically to draw attention to a visible place, object or person who has just appeared, approached or arrived, or when you have found something you were looking for. In this case you put them at the beginning of the sentence and you stress them.", "Italian: for the same purpose, to communicate what just happened, we prefer to use 'ecco' instead of c'è or 'eccoli' instead of 'ci sono'. 'c'è Jola' means just that Jola is there (there's Jola), but not that she has just arrived. 'ecco Jola' means 'Oh, look, Jola has just arrived!'."]],
 ['def', "here they are!", "da sind sie!", "eccoli!", ["E.g. imagine you are looking for a group of people, you say this once you finally find them.", "In German you put 'da' at the beginning to stress it, followed by 'sind' and 'sie' at the end.", "In Italian, instead of 'sono là/lì' (which is also correct) or 'là/lì sono' (which puts the stress on 'là/lì', meaning 'they are right there'), or simply 'ci sono', you use 'eccoli!', which is a more emphatic way to communicate your finding like 'look, here they are!'. Note 'li' is a suffix that means 'them' or 'to them'."]],
 ['def', "Here I am!", ["da bin ich!", "hier bin ich!"], ["eccomi", "eccomi qui", "eccomi qua"], "Means, 'Look, I am just arrived (here)'. This nuance in meaning is expressed in both German and English by altering the word order (even more in German than in English), but in Italian word order is generally not as free as in German, we prefer to use another word, 'ecco'. 'mi' means 'me'."],
 ['tra', "are you there tomorrow?", "bist du morgen da?", "ci sei domani?", "Here 'there' means a place established by context or mentioned previously by the people talking. The question may mean 'are you attending tomorrow?', 'are you going to take part tomorrow?'."],
 ['def', "the concert", "das Konzert", "il concerto", "English: stress on the 'o'. Both German and Italian: stress on the 'e'."],
 ['def', "are you attending the concert tomorrow?", "bist du auf dem Konzert morgen?", "ci sei al concerto domani?", ["German: 'das Konzert' is 'the concert', but 'at the concert' is actually 'at to the concert'; 'auf' means 'at' and 'dem' means 'to the': 'auf dem Konzert'. 'Auf das Konzert' is wrong in this context because whenever 'auf' means 'at', it has to be followed by 'to'. 'Auf das Konzert' means 'to the concert' and can only be used when you mean moving or getting there, not staying there.", "In informal Italian 'to be there at', 'esserci a' can be used to mean 'to take part in', 'to attend', the word 'ci' (there) gives this specific meaning of to go, to attend, to take part. Note 'al' is the contraction of 'a il', meaning 'to the': 'the concert', 'il concerto', but 'to the concert', 'a il concerto' &rarr; 'al concerto'."]],
 ['tra', "to come", "kommen", "venire"],
 ['tra', "you come", "du kommst", "vieni"],
 ['tra', "are you coming?", "kommst du?", "vieni?"],
 ['tra', "are you coming to the concert tomorrow?", "kommst du auf das Konzert morgen?", "vieni al concerto domani?", "When 'auf' means 'to' rather than 'at' quite logically no other 'to' is added, otherwise it would be like saying 'to' two times: 'to to'. In this case this implies 'das' remains 'das': kommen auf das Konzert, to come to the concert, venire al concerto."],
];
