/*

Structural language learning and tandem method.
A JavaScript computer program for coaching.

Copyright (c) 2012 Antonio Bonifati http://ninuzzo.github.com/about.html

This work is licensed under the Creative Commons
Attribution-NonCommercial-ShareAlike 3.0 Unported License. To view a copy of
this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a
letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View,
California, 94041, USA.

*/

var title="Talking about likes and dislikes",
  date='2012-05-18', lk='en', l1='de', l2='it', lesson=
[
 ['def', "to like", "mögen", "piacere", "Italian: 'piacere' also means 'pleasure': the pleasure, il piacere."],
 ['def', "I like", "ich mag", "mi piace", ["German: mögen &rarr; ich mag, irregular", "Italian: it pleases me &rarr; (it) pleases to me &rarr; (esso/essa) piace a me &rarr; (it) to me pleases &rarr; (esso/essa) mi piace &rarr; to me pleases (it) &rarr; mi piace (esso/essa). 'It' (esso/essa for a thing or wild animal) is often understound. 'mi' is 'to me' and equivalent to 'a me', but with less stress on 'me': 'piace a me' is also correct but used less frequently, only when there is a need to stress 'me', e.g. 'piace a me come a te' is preferred to 'mi piace come ti piace'. It means 'I like it as you like it'. If you say 'esso/essa piace', without saying 'who' likes the thing, it means 'it is liked' by everbody or almost everybody, 'it is generally liked'."]],
 ['def', "I like it", "ich mag es", "mi piace", ["German: same structure as English.", "Italian: 'it' is understood, but again notice the sentence structure which is flipped: (it) pleases (to) me, (it) (to) me pleases. What in English is the subject (I) becomes the object in Italian ((to) me, a me after piace or simply mi before piace). What in English is the object (it) becomes the subject in Italian, often understood and for emphasis put at the end of the sentence rather than the beginnin: mi piace esso. Remember this inversion. Piacere is always used in this inverted and reflexive way in Italian, like to please in English. This is a little complication you have to get used with. You may just want to learn that 'I like' is 'mi piace', without too much thinking, but it is good for you to know the structure. BTW 'mi piace a me', 'a me mi piace' are wrong if said with a plain tone, because 'mi' already means 'a me', so saying it two times is redundant. Unless you stress 'me' in 'a me' and you put a small pause, marked by a comma: a me, mi piace. This is perfectly correct. Here, the 'a me' part means 'as of me', 'if you want my opinion', 'as far as I'm concerned', etc. It is not a mere repetition and picky grammarians ought to accept it!"]],
 ['def', "the music", "die Musik", "la musica", ["German: stress on 'i' to be correct, but colloquially on 'u' as in English, but still a plain 'oo' sound, not a 'you' sound.", "Italian: stress always on 'u'."]],
 ['tra', "I like music", "ich mag Musik", "mi piace la musica", ["German: no article when speaking in general, as in German.", "Italian: I like the music. 'The' is needed both, even if talking generally."]],
 ['tra', "I like Beethoven's music", "ich mag die Musik von Beethoven", "mi piace la musica di Beethoven", ["German: with a specific kind of music, the article is needed. And with proper nouns without 'the' use 'von' for 'of'.", "Italian: I like the music of Beethoven. A's B is 'B of A' in Italian."]],
 ['def', "much", "sehr", ["molto", "tanto"], "Italian: they are the same, with 'tanto' being a bit more informal."],
 ['def', "very much", "sehr", ["moltissimo", "tantissimo"], ["German: you do not usually translate 'very' directly, although in context they may be other indirect ways to say 'very'. E.g. if you want to say 'thank you very much', that is 'danke schön', 'thanks beautifully' or 'vielen dank', 'many thanks'.", "Italian: you can still simply say 'molto/tanto' for 'very much' as well as 'much'. If you want to translate 'very' - this is done especially in informal language - substitute -o for -ìssimo and note stress goes on the first 'i'."]],
 ['tra', "I like music very much", "ich mag sehr Musik", ["mi piace molto la musica", "mi piace moltissimo la musica", "mi piace tanto la musica", "mi piace tantissimo la musica"], ["English: or, informally, 'a lot'. 'Very much' must be put at the end.", "German: sehr goes before Musik, just as in Italian!", "Italian: mind much or very much go before 'the music'! You can use both words for much and very much, four alternatives in total. 'The music' can also go at the beginning of the sentence for stressing the subject."]],
 ['tra', "I like it", "ich mag es", "mi piace"],
 ['tra', "I don't like it", "ich mag es nicht", "non mi piace", ["Both German and Italian do not use to do to make negative sentences, you just put 'not'. In more formal English you can say: I dislike it.", "German: I like it not", "Italian: not to me pleases. The subject (it) can go either at the end or the beginning, but it is more often understood."]],
 ['def', "to cook", "kochen", "cucinare", ["German: o is short because there are two consonants following. It is very similar to English, you just add the usual -en ending for whole verbs and the 'k' because a guttural 'ch' as in Scottish Loch.", "Italian: stress on 'a', kutSinàre."]],
 ['tra', "I cook", "ich koche", "cucino", ["German: -en &rarr; -e.", "Italian: -are &rarr; -o."]],
 ['tra', "I like cooking", ["ich mag kochen", "ich koche gern"], "mi piace cucinare", ["Germans like to use 'gern', 'gladly', 'happily' and so the sentence 'I cook gladly' is a more common way to say 'I like cooking', but both are correct. 'gern' or 'gerne' is the same, you choose.", "Italian: 'I like to cook' which becomes '(it) to me pleases to cook', there is no -ing form in Italian, we just use the full verb."]],
 ['def', "gladly", ["gern", "gerne"], ["volentieri", "con piacere"], "Italian: con piacere means 'with pleasure' and volentieri (stress on ie, which sounds like ye in yes) 'with will', 'voluntarily'. In fact 'to want', 'to have the will' is 'volere'. 'ich koche gern(e)' would be 'cucino con piacere' or 'cucino volentieri' but you actually use it in Italian only if you want to offer your help to cook, e.g. if you are asked 'do *you* want to cook?' you can say 'yes, cucino volentieri/con piacere'. While in German it is still a general statement meaning 'I like cooking'. For this latter meaning it is more common to say 'mi piace cucinare' in Italian."],
 ['def', "I like cooking pasta", ["ich koche Nudeln gerne", "ich mag Nudeln kochen"], "mi piace cucinare la pasta", ["German: 'pasta' is countable in German: a piece of pasta is die Nudel (like nnoodles, which in English is just a long kind of pasta), but pasta is die Nudeln and the plural goes here because there are a lot of pieces of pasta in a dish of pasta.", "Italian: 'I like to cook the pasta'. 'La pasta' is mostly singular, 'le paste' is not wrong, in reference to different kinds/brands of pasta products, but 'a dish/plate of pasta' is always singular in Italian as in English: 'un piatto di pasta' (ia sounds like ya)."]],
 ['def', "to eat", "essen", "mangiare", ["German: Essen is also a city in Western Germany, in the Ruhr region, but it seems its name has nothing to do with eating. Its ancient name was Astnide and slowly transformed into Astnidum, Assinde, Essendia e Esnede. BTW in German 'das Essen' means food.", "Italian: 'i' is silent here: mandZàre."]],
 ['tra', "I like eating", ["ich esse gerne", "ich mag essen"], "mi piace mangiare"],
 ['tra', "I don't like cooking, but I like eating", ["ich koche nicht gerne, aber ich esse gerne", "ich mag nicht kochen, aber ich mag essen"], ["non mi piace cucinare, ma mi piace mangiare", "cucinare non mi piace, ma mi piace mangiare"]],
 ['def', "I like cooking, but I like eating better", ["ich koche gerne, aber esse lieber", "ich koche gerne, aber ich esse lieber", "ich esse lieber als ich koche", "ich esse lieber als koche"], ["mi piace cucinare, ma mi piace di più mangiare", "mi piace cucinare, ma mangiare mi piace di più"], ["In both languages, there is a word for 'better' as in 'to feel better' (besser, meglio), but it is not used in this case, when expressing likings to a better degree. Italian uses 'of more/plus', that is 'di più' - you cannot say 'piacere meglio'. You have to say 'piacere di più'. German uses the construction with 'more gladly', which is a specific irregular word: lieber.", "German: 'ich' can be left out in the second sentence. 'lieber gerne' is wrong, you cannot put a second 'gerne' or 'gern' because 'lieber' means 'more gladly', 'più volentieri', 'con più piacere'! The last two options are, literally, I eat more gladly than (I) cook, or in unlikely but correct Italian: mangio di più di quanto cucino (I eat of more of how (I) cook) or mangio più volentieri/con più piacere di quanto cucino (I eat more gladly of how (I) cook). These are both unlikely in Italian. BTW when is quando, but how is quanto."]],
 ['def', ["I prefer eating to cooking", "I would rather eat than cook"], "TODO", ["preferisco mangiare che cucinare", "preferisco mangiare piuttosto che cucinare"], ["Here is another way to say the same thing.", "Italian: rather is piuttòsto and it is a nice addition to che (that), the sentence sounds more complete if you add it. In other words when the alternatives are verbs rather than nouns, Italian uses piuttosto che=rather than instead of 'to', which is 'a' and can be used only for nouns: preferisco il pane _alla_/_piuttosto che la_ pasta=I prefer bread to pasta. 'preferisco mangiare a cucinare' would sound strange, 'a' cannot be be used with verbs (here we have mangiare and cucinare). (io) prefer-isc-o is irregular from preferire, an -isc-  (pronounced like -isc of 'disc') is added."]],
 ['tra', "I like it", ["ich mag es", "es gefällt mir", "das gefällt mir"], "mi piace", "German: you can also use gefallen, die Gefallen means pleasure but also favour, just like piacere in Italian! gefallen is always followed by a 'to', so it is 'to me' or 'mir'. gefallen irregularly becomes er/sie/es gefällt, the ä is stressed and pronounced like 'e', as in English 'bed'. Note how 'es gefällt mir' and 'esso piace a me' (it pleases to me) have the same structure and word order. 'esso piace a me' is correct in Italian, but then it undergoes other two transformations: esso is left understood and 'a me' if not stressed becomes 'mi' and shifts before the verb 'piace'."],
 ['tra', "I don't like it", ["ich mag es nicht", "es gefällt mir nicht", "mir gefällt es nicht"], ["non mi piace", "a me non piace"], ["German: To stress 'mir' you put it at the beginning. Informally you use the contracted version: mag es &rarr; mag's. 'ich mag nicht es' is not very common, you usually do not put nicht before the object, unless you are in an unlikely context where you need to stress nicht.", "Italian: I not like, or better (it) not to me pleases. If you want to stress that *you* do not like it, you use 'a me' instead of 'mi' in Italian and put it at the beginning. 'a me non mi piace' is wrong, unless it is 'a me (stress), (pause) non mi piace'."]],
 ['def', ["I like it very much", "I like it a lot"], ["es gefällt mir gut", "das gefällt mir gut"], ["mi piace moltissimo"], ["English: 'a lot' is informal", "German: it pleases to me good.", "Italian: also tantissimo, tanto or just molto, the latter especially in formal situations."]],
 ['def', "to love", "lieben", "amare"],
 ['tra', "I love it", "ich liebe es", ["l'amo", "l'adoro"], ["German:", "Italian: when you say l'amo or l'adoro, it depends on the context whether you are referring to a thing or person, because 'lo' means both 'esso' or 'lui'. 'la' means 'essa', 'lei', but both 'lo' and 'la' before vowel often - but not necessarily - get elided into l' and this introduces even more ambiguity. Amare can be used for both things and people in Italian as in the other two languages. A bit less strong is adorare, to adore or you could simply say 'mi piace moltissimo/tantissimo' for 'I love it'."]],
 ['tra', "you love it", ["du liebst es", "Sie lieben es"], ["l'ami", "tu l'ami", "Lei l'ama"], ["German: lieb-en &rarr; du lieb-st, regularly. Formal 'you': Sie lieben.", "Italian: am-are &rarr; (tu) am-i, regularly. Formal 'you': Lei am-a."]],
 ['def', "I will love", "ich werde lieben", ["io amerò", "amerò"], ["English: you make the future using another verb, to will, as if you have a will in the future to do something or be in a certain state.", "German: as in English you use another verb, but a different one, werden, which by itself means 'to become'. So you become something or by extension do something in the future.", "Italian: we do not use another verb, but just a different ending. I'm loving, I love=(io) am-o, I'll love=(io) am-erò, both regularly."]],
 ['def', "you will love", ["du wirst lieben", "Sie werden lieben"], ["tu amerai", "amerai", "Lei amerà"], ["German: wirst, not werdst. It is irregular!", "Italian: am-are &rarr; (tu) am-i &rarr; (tu) am-erài, both regular."]],
 ['tra', "you will love it", ["du wirst es lieben", "Sie werden es lieben"], ["l'amerai", "l'amerà"], "Italian: tu and Lei can be espressed as well: tu l'amerai, Lei l'amerà. l' is the contraction of either 'lo' (masculine person or thing) or 'la' (feminine person or thing)."],
 ['tra', "thank you", "danke", "grazie"],
 ['tra', "thank you too", "danke dir auch", "grazie anche a te", "Italian: you can only say 'grazie a te, anche' if you forget to say anche (too, as well) and you want to put it after a pause as a late addition. But most commonly put 'too' before 'to you', unlike English and German."],
];
